jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Project
      uses: actions/checkout@v4
    - continue-on-error: true
      id: meta
      name: Generate Docker Meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: 'type=ref,event=branch

          type=semver,pattern={{version}}

          type=semver,pattern={{major}}.{{minor}}

          type=semver,pattern={{major}}

          type=sha

          '
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - continue-on-error: true
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3.1.0
    - continue-on-error: true
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3.0.0
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - continue-on-error: true
      name: Build and Push Docker image
      uses: docker/build-push-action@v5.2.0
      with:
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
name: Build Docker Container
on:
  repository_dispatch:
    types: trigger-ga___build_container.yml
