jobs:
  Format-Code:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: extract_branch
      name: Extract branch name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache gradle files
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties',
          '**/*.accesswidener') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          ./.gradle/loom-cache

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Format Code
      run: ./gradlew -PskipHandbook=1 && ./gradlew spotlessApply -PskipHandbook=1
    - continue-on-error: true
      run: git config --global user.name "github-actions"
    - continue-on-error: true
      run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - continue-on-error: true
      run: git stash
    - continue-on-error: true
      run: git checkout ${{ steps.extract_branch.outputs.branch }} && git pull
    - continue-on-error: true
      run: git stash pop || true
    - continue-on-error: true
      name: Commit Code Changes
      run: git add -u && git commit -m 'Format code [skip actions]' || true
    - continue-on-error: true
      name: Push Code Changes
      run: git push --set-upstream --force origin ${{ steps.extract_branch.outputs.branch
        }}
  Update-Languages:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: extract_branch
      name: Extract branch name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      name: Update Languages
      run: python scripts/manage_languages.py -u
    - continue-on-error: true
      run: git config --global user.name "github-actions"
    - continue-on-error: true
      run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - continue-on-error: true
      run: git stash
    - continue-on-error: true
      run: git checkout ${{ steps.extract_branch.outputs.branch }} && git pull
    - continue-on-error: true
      run: git stash pop || true
    - continue-on-error: true
      name: Commit any language changes
      run: git add -u && git commit -m 'Update languages [skip actions]' || true
    - continue-on-error: true
      name: Push language changes
      run: git push --set-upstream --force origin ${{ steps.extract_branch.outputs.branch
        }}
name: Lint & Format Code
on:
  repository_dispatch:
    types: trigger-ga___check_code.yml
