jobs:
  Build-Handbook:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - continue-on-error: true
      name: Cache node modules
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: '~/.npm

          ~/.cache

          '
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      name: Install dependencies
      run: npm install --force
      working-directory: src/handbook
    - continue-on-error: true
      name: Download Avatar Data
      uses: suisei-cn/actions-download-file@v1.4.0
      with:
        target: src/handbook/data/
        url: https://api.grasscutter.io/static/avatars.csv
    - continue-on-error: true
      name: Download Command Data
      uses: suisei-cn/actions-download-file@v1.4.0
      with:
        target: src/handbook/data/
        url: https://api.grasscutter.io/static/commands.json
    - continue-on-error: true
      name: Download Entity Data
      uses: suisei-cn/actions-download-file@v1.4.0
      with:
        target: src/handbook/data/
        url: https://api.grasscutter.io/static/entities.csv
    - continue-on-error: true
      name: Download Item Data
      uses: suisei-cn/actions-download-file@v1.4.0
      with:
        target: src/handbook/data/
        url: https://api.grasscutter.io/static/items.csv
    - continue-on-error: true
      name: Download Scene Data
      uses: suisei-cn/actions-download-file@v1.4.0
      with:
        target: src/handbook/data/
        url: https://api.grasscutter.io/static/scenes.csv
    - continue-on-error: true
      name: Download Quest Data
      uses: suisei-cn/actions-download-file@v1.4.0
      with:
        target: src/handbook/data/
        url: https://api.grasscutter.io/static/quests.csv
    - continue-on-error: true
      name: Download Main Quest Data
      uses: suisei-cn/actions-download-file@v1.4.0
      with:
        target: src/handbook/data/
        url: https://api.grasscutter.io/static/mainquests.csv
    - continue-on-error: true
      name: Build handbook
      run: npm run build
      working-directory: src/handbook
    - continue-on-error: true
      name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: Handbook
        path: src/handbook/dist/*.html
  Lint-Code:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      id: extract_branch
      name: Extract branch name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - continue-on-error: true
      name: Cache node modules
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: '~/.npm

          ~/.cache

          '
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      name: Install dependencies
      run: npm install --force
      working-directory: src/handbook
    - continue-on-error: true
      name: Run linter
      run: npm run lint
      working-directory: src/handbook
    - continue-on-error: true
      run: git config --global user.name "github-actions"
    - continue-on-error: true
      run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - continue-on-error: true
      run: git stash
    - continue-on-error: true
      run: git checkout ${{ steps.extract_branch.outputs.branch }} && git pull
    - continue-on-error: true
      run: git stash pop || true
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: Commit changes
      run: git add -u && git commit -m "Lint Code [skip actions]" || true
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: Push changes
      run: git push --set-upstream --force origin ${{ steps.extract_branch.outputs.branch
        }}
name: Handbook
on:
  repository_dispatch:
    types: trigger-ga___handbook.yml
