jobs:
  run:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: superbrothers/close-pull-request@v3
      with:
        comment: This PR has been closed for modifying protected files. See `CONTRIBUTING.md`
          for more information.
name: Protect write-access files from being PR'd
on:
  repository_dispatch:
    types: trigger-ga___protect_files.yml
